### PR TITLE
Fix GitHub actions build

### PR DESCRIPTION
**Pull request by afh**
@peterkeen and @tbm this PR is now ready for review. Hopefully I've been able to clean-up the commit history so that why changes were is self-explanatory. If it isn't please ask; I'm happy to answer any questions.

The changes in commit [`014b80ed`](https://github.com/ledger/ledger-website/pull/53/commits/014b80ed109377819bc8c4c10e2c4c88d03bc100) is tested when this PR is merged to master. If you'd like to take any precautions prior to doing that I'm happy to think about how that may be achieved.

# ⚠️ Nota Bene
- [x] This PR depends on [`ledger#2208`](https://github.com/ledger/ledger/pull/2208) to have been merged. Once it has this PR needs to be updated so that commit [`e6b2f3aa8`](https://github.com/ledger/ledger-website/pull/53/commits/e6b2f3aa8032d5bdb3bcc554dc5cc57637dbd2eb) is reverted/removed from this PR.

### CODE REVIEW

**Review by tbm — APPROVED** [review]
Looks good to me but I think @peterkeen is in a better position to review this.

Thanks for working on this.

**Comment by tbm** [comment]
Note that I applied the change on the ledger side so one commit needs to be reverted

**Review by peterkeen — APPROVED** [review]
Looks good!

**Comment by afh** [comment]
Thanks @peterkeen and @tbm for your review. I've reverted the [e6b2f3aa8](https://github.com/ledger/ledger-website/pull/53/commits/e6b2f3aa8032d5bdb3bcc554dc5cc57637dbd2eb) commit and the files needed to generate `version.texi` have been fetched from `ledger/ledger@master` in the [latest GitHub Actions build](https://github.com/ledger/ledger-website/actions/runs/4334776307/jobs/7568901911).

@peterkeen I'm uncertain how to test the deployment, happy to bounce around ideas,  and happy to coordinate a point in time where we both are online (I reside in [CET](https://www.timeanddate.com/time/zones/cet)) and can potentially establish synchronous communication to resolve unexpected issues more directly in case things go wrong.

**Comment by afh** [comment]
☝️ This PR contains an important security fix (upgrade rack to 2.2.6.3) recommended by dependabot, for details see #57.

**Comment by tbm** [comment]
I think that was ready to be merged.

**Comment by afh** [comment]
Thanks for merging, @tbm!

**Pull request merged**
