### PR TITLE
Minor cleanup

### PR DESCRIPTION
**Pull request by afh**
* Remove libgmp dependency in .travis.yml
* Add bundler directories to .gitignore

Do these changes also make sense from your point of view?

### CODE REVIEW

**Comment by jwiegley** [comment]
@afh Hi Alexis! How does Ledger build without `libgmp-dev`?

**Comment by peterkeen** [comment]
@jwiegley the website doesn't build ledger and doesn't use hakyll anymore, so libgmp is almost certainly unnecessary.

**Comment by jwiegley** [comment]
Thanks, @peterkeen, I forgot to which repository this applied. :)

**Comment by afh** [comment]
Thanks for merging @peterkeen 

@jwiegley 😆

**Pull request merged**
