### PR TITLE
Change paths to 3.3

### PR DESCRIPTION
**Pull request by afh**
I'm open to changing the paths to `3.x` in case we want to avoid changing them on very minor version update of ledger.

### CODE REVIEW

**Comment by tbm** [comment]
I'd probably just use `3` or in fact nothing at all (maybe it's also time to remove the 2.x docs. Nobody is supposed to use 2.x anymore).

**Comment by afh** [comment]
If the 2.x docs are removed is there any value in keeping the 3? Couldn't it just be `doc`? The likeliness of [`ledger/ledger4`](https://github.com/ledger/ledger4) seeing use outside of development seems small.

**Comment by tbm** [comment]
> If the 2.x docs are removed is there any value in keeping the 3? Couldn't it just be doc

Yes, that's what I was trying to suggest.   Sorry, my message wasn't so coherent because it was a train of though (let's use `3`, actually, why not remove `2` and just have docs).

So, yes, I'd be in favour of just `/doc`, plus a redirect from the old `3.0`.  (I'm not sure what to do about `2.6`? Maybe a placeholder page telling people that 2.x is obsolete?)

**Comment by afh** [comment]
ℹ️ I'll clean up the commits of this PR and will re-request review.

**Comment by afh** [comment]
Closing in favor of #53

**Pull request closed without merging**
