### PR TITLE
Replace build_docs.sh script with Makefile

### PR DESCRIPTION
**Pull request by afh**
Here's my proposal to replace the `build_docs.sh` script with a Makefile, which improves the build in that in builds the documentation in parallel.

What are your thoughts on this?

### CODE REVIEW

**Comment by jwiegley** [comment]
I think this should really be a `CMakeLists.txt` file in the doc directory, since we don't require make anywhere else.

**Comment by peterkeen** [comment]
I wrote build_docs.sh because, as the website maintainer, I need to understand the thing I'm working on when I'm maintaining it. A shell script is straightforward, if slow I guess. Deploys take just a few minutes on Travis and I doubt parallelizing it makes a difference.

**Comment by jwiegley** [comment]
@afh Then also please ignore my comment elsewhere about `CMakeLists.txt`

**Comment by afh** [comment]
Thanks for merging @peterkeen.

@jwiegley FYI: I've introduced [convenience Makefiles](https://github.com/afh/ledger/tree/wip/python3/makefiles) to make building ledger easier (for me 😬) with the [Python 3 related changes](https://github.com/afh/ledger/tree/wip/python3/).

**Pull request merged**
