### PR TITLE
Update homepage code sample

### PR DESCRIPTION
**Pull request by leowzukw**
Update date of the transaction, to show that project is active/modern/...

### CODE REVIEW

**Comment by afh** [comment]
The date in the output example below the text 'or the history of a particular account:' should also be updated.

**Comment by afh** [comment]
Additionally the status badge links to the [Github Activity](https://github.com/ledger/ledger/pulse/monthly).

**Comment by afh** [comment]
Can you please provide a single commit for the changes.

**Comment by leowzukw** [comment]
Yes sure

**Comment by leowzukw** [comment]
Should be ok now.

**Comment by afh** [comment]
Great. Thank you for your contribution. The changes should be live within the next hour or the next two days the latest.

**Comment by simonmichael** [comment]
Good idea!

**Comment by leowzukw** [comment]
Thanks

**Pull request merged**
